default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: jwt_devise_development

test:
  <<: *default
  database: db/jwt_devise_test

production:
  <<: *default
  database: db/jwt_devise_production
